const queryParamsData = [
  {
    dictName: '',
    operateType: '',
    paramEn: 'goodsName',
    paramZh: '商品名称',
    queryType: 'el-input',
    timeParam1: '',
    timeParam2: '',
    timeParamCount: 0,
  },
  {
    dictName: 'isNewDict',
    operateType: '1',
    paramEn: 'isNew',
    paramZh: '是否新品',
    queryType: 'el-select',
    timeParam1: '',
    timeParam2: '',
    timeParamCount: 0,
  },
  {
    dictName: '',
    operateType: '2',
    paramEn: 'createTime',
    paramZh: '创建时间',
    queryType: 'el-date-picker',
    timeParam1: 'startTime',
    timeParam2: 'endTime',
    timeParamCount: 2,
  },
  {
    dictName: '',
    operateType: '',
    paramEn: 'isHot',
    paramZh: '是否热门',
    queryType: 'el-select',
    timeParam1: '',
    timeParam2: '',
    timeParamCount: 0,
  },
]
