const payload = {
  "apiFileRoot": "@/apis/goods/index.ts",
  "viewFileRoot": "@/views/goods/index.vue",
  "isNeedElTable": "1",
  "tableRowColumnCount": 4,
  "tableData": [
    {
      "paramEn": "goodsName",
      "paramZh": "名称",
      "showType": "text",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "goodsImageUrl",
      "paramZh": "图片",
      "showType": "image-preview",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "goodsStatus",
      "paramZh": "状态",
      "showType": "dict-tag",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "goods_status",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "isHot",
      "paramZh": "是否热门",
      "showType": "el-tag",
      "iconName": "hot",
      "elTagTheme": "primary",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "isOpen",
      "paramZh": "是否开启",
      "showType": "el-switch",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "green",
      "switchOffColor": "red",
      "switchActiveValue": "0",
      "switchActiveText": "上架",
      "switchInactiveValue": "1",
      "switchInactiveText": "下架"
    }
  ],
  "isNeedElDescriptions": "0",
  "descriptionsRowColumnCount": 2,
  "descriptionsData": []
}

const payload = {
  "apiFileRoot": "@/apis/goods/index.ts",
  "viewFileRoot": "@/views/goods/index.vue",
  "isNeedElTable": "1",
  "tableRowColumnCount": 4,
  "tableData": [
    {
      "paramEn": "goodsName",
      "paramZh": "名称",
      "showType": "text",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "goodsImageUrl",
      "paramZh": "图片",
      "showType": "image-preview",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "goodsStatus",
      "paramZh": "状态",
      "showType": "dict-tag",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "goods_status",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "isHot",
      "paramZh": "是否热门",
      "showType": "el-tag",
      "iconName": "hot",
      "elTagTheme": "primary",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "isOpen",
      "paramZh": "是否开启",
      "showType": "el-switch",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "green",
      "switchOffColor": "red",
      "switchActiveValue": "0",
      "switchActiveText": "上架",
      "switchInactiveValue": "1",
      "switchInactiveText": "下架"
    }
  ],
  "isNeedElDescriptions": "1",
  "descriptionsRowColumnCount": 6,
  "descriptionsData": [
    {
      "paramEn": "orderNo",
      "paramZh": "订单号",
      "showType": "text",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "orderImage",
      "paramZh": "订单图片",
      "showType": "image-preview",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    },
    {
      "paramEn": "orderStatus",
      "paramZh": "订单状态",
      "showType": "dict-tag",
      "iconName": "",
      "elTagTheme": "",
      "dictName": "order_status",
      "switchOnColor": "",
      "switchOffColor": "",
      "switchActiveValue": "",
      "switchActiveText": "",
      "switchInactiveValue": "",
      "switchInactiveText": ""
    }
  ]
}
